apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-frontend
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/deviant101/ArgoCD-App-of-Apps.git
    targetRevision: main
    path: k8s/app1-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
