apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/deviant101/ArgoCD-App-of-Apps.git
    targetRevision: main
    path: k8s/app2-api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: app2-api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
